### ISSUE TITLE
Plug.Swoosh.MailboxPreview.init/1 is undefined

### ISSUE THREAD

**Issue by Hermanverschooten** [swoosh/swoosh#803]
### Describe the bug

I recently switch from cowboy to bandit and it seems that since then `Plug.Swoosh.MailboxPreview` is no longer available, which is odd, as bandit also depends on `plug`, and that is what you check for.

### Steps to Reproduce the Bug or Issue

Switch from cowboy to bandit.

### Platform

- OTP: 26.0.2
- Elixir: 1.15.4

**Comment by princemaple** [comment]
Does your project compile properly? I can't seem to compile my tiny test project when bandit is present.

**Comment by Hermanverschooten** [comment]
Yes, it compiles without any problems. I just get a warning, and ofcourse the preview doesn't work anymore.

**Comment by princemaple** [comment]
Could you provide me with a minimal reproduction project? Cheers.

**Comment by Hermanverschooten** [comment]
I wish I could, but I can't. It is very strange I had this in at least 2 projects where I swapped cowboy with bandit.
But when I make a new phoenix 1.7.7 project and do the 2 changes needed, replace plug_cowboy with bandit and add the adapter in config.exs, it now compiles perfectly. Il'll say even more. I nuked my _build, deps and .elixir_ls files in one of these projects and did a rebuild and the error has gone.

**Comment by princemaple** [comment]
Feel free to reopen if a repro is found. :)

**Comment by mjrusso** [comment]
I've run into this same issue and after some trial-and-error found a way to reproduce it. This example uses Phoenix 1.7.7:

``` bash
$ mix phx.new foo
$ cd foo
$ mix ecto.create
$ mix compile --warnings-as-errors --force
Compiling 15 files (.ex)
Generated foo app
```

Next, swap in Bandit: 

``` diff
diff --git a/config/config.exs b/config/config.exs
index da97882..67f842d 100644
--- a/config/config.exs
+++ b/config/config.exs
@@ -12,6 +12,7 @@ config :foo,
 
 # Configures the endpoint
 config :foo, FooWeb.Endpoint,
+  adapter: Bandit.PhoenixAdapter,
   url: [host: "localhost"],
   render_errors: [
     formats: [html: FooWeb.ErrorHTML, json: FooWeb.ErrorJSON],
diff --git a/mix.exs b/mix.exs
index ace976b..faf5495 100644
--- a/mix.exs
+++ b/mix.exs
@@ -49,7 +49,7 @@ defmodule Foo.MixProject do
       {:telemetry_poller, "~> 1.0"},
       {:gettext, "~> 0.20"},
       {:jason, "~> 1.2"},
-      {:plug_cowboy, "~> 2.5"}
+      {:bandit, "~> 1.0-pre"}
     ]
   end
```

``` bash
$ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.084s
New:
  bandit 1.0.0-pre.14
  thousand_island 1.0.0-pre.7
Unchanged:
  castore 1.0.3
  db_connection 2.5.0
  decimal 2.1.1
  ecto 3.10.3
  ecto_sql 3.10.2
  esbuild 0.7.1
  expo 0.4.1
  file_system 0.2.10
  finch 0.16.0
  floki 0.34.3
  gettext 0.23.1
  hpax 0.1.2
  jason 1.4.1
  mime 2.0.5
  mint 1.5.1
  nimble_options 1.0.2
  nimble_pool 1.0.0
  phoenix 1.7.7
  phoenix_ecto 4.4.2
  phoenix_html 3.3.2
  phoenix_live_dashboard 0.8.1
  phoenix_live_reload 1.4.1
  phoenix_live_view 0.19.5
  phoenix_pubsub 2.1.3
  phoenix_template 1.0.3
  plug 1.14.2
  plug_crypto 1.2.5
  postgrex 0.17.3
  swoosh 1.11.5
  tailwind 0.2.1
  telemetry 1.2.1
  telemetry_metrics 0.6.1
  telemetry_poller 1.0.0
  websock 0.5.3
  websock_adapter 0.5.4
* Getting bandit (Hex package)
* Getting thousand_island (Hex package)
```

And recompile:

``` bash
$ mix compile --warnings-as-errors --force
==> thousand_island
Compiling 16 files (.ex)
Generated thousand_island app
==> bandit
Compiling 48 files (.ex)
Generated bandit app
==> websock_adapter
Compiling 2 files (.ex)
Generated websock_adapter app
==> phoenix
Compiling 71 files (.ex)
Generated phoenix app
==> phoenix_live_reload
Compiling 4 files (.ex)
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  lib/phoenix_live_reload/application.ex:32: Phoenix.LiveReloader.Application.start_link/0

Generated phoenix_live_reload app
==> phoenix_live_view
Compiling 37 files (.ex)
Generated phoenix_live_view app
==> phoenix_live_dashboard
Compiling 36 files (.ex)
Generated phoenix_live_dashboard app
==> foo
Compiling 15 files (.ex)
Generated foo app
```

Next, let's add Hackney (here's where the problems start):

``` diff
diff --git a/mix.exs b/mix.exs
index faf5495..66f53db 100644
--- a/mix.exs
+++ b/mix.exs
@@ -49,7 +49,8 @@ defmodule Foo.MixProject do
       {:telemetry_poller, "~> 1.0"},
       {:gettext, "~> 0.20"},
       {:jason, "~> 1.2"},
-      {:bandit, "~> 1.0-pre"}
+      {:bandit, "~> 1.0-pre"},
+      {:hackney, "~> 1.9"}
     ]
   end
```

``` bash
$ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.227s
New:
  certifi 2.12.0
  hackney 1.18.2
  idna 6.1.1
  metrics 1.0.1
  mimerl 1.2.0
  parse_trans 3.4.1
  ssl_verify_fun 1.1.7
  unicode_util_compat 0.7.0
Unchanged:
  bandit 1.0.0-pre.14
  castore 1.0.3
  db_connection 2.5.0
  decimal 2.1.1
  ecto 3.10.3
  ecto_sql 3.10.2
  esbuild 0.7.1
  expo 0.4.1
  file_system 0.2.10
  finch 0.16.0
  floki 0.34.3
  gettext 0.23.1
  hpax 0.1.2
  jason 1.4.1
  mime 2.0.5
  mint 1.5.1
  nimble_options 1.0.2
  nimble_pool 1.0.0
  phoenix 1.7.7
  phoenix_ecto 4.4.2
  phoenix_html 3.3.2
  phoenix_live_dashboard 0.8.1
  phoenix_live_reload 1.4.1
  phoenix_live_view 0.19.5
  phoenix_pubsub 2.1.3
  phoenix_template 1.0.3
  plug 1.14.2
  plug_crypto 1.2.5
  postgrex 0.17.3
  swoosh 1.11.5
  tailwind 0.2.1
  telemetry 1.2.1
  telemetry_metrics 0.6.1
  telemetry_poller 1.0.0
  thousand_island 1.0.0-pre.7
  websock 0.5.3
  websock_adapter 0.5.4
* Getting hackney (Hex package)
* Getting certifi (Hex package)
* Getting idna (Hex package)
* Getting metrics (Hex package)
* Getting mimerl (Hex package)
* Getting parse_trans (Hex package)
* Getting ssl_verify_fun (Hex package)
* Getting unicode_util_compat (Hex package)
```

``` bash
$ mix compile --warnings-as-errors --force
===> Analyzing applications...
===> Compiling unicode_util_compat
===> Analyzing applications...
===> Compiling idna
===> Analyzing applications...
===> Compiling mimerl
==> ssl_verify_fun
Compiling 7 files (.erl)
Generated ssl_verify_fun app
===> Analyzing applications...
===> Compiling certifi
===> Analyzing applications...
===> Compiling parse_trans
===> Analyzing applications...
===> Compiling metrics
===> Analyzing applications...
===> Compiling hackney
==> swoosh
Compiling 44 files (.ex)
Generated swoosh app
==> foo
Compiling 15 files (.ex)
warning: Plug.Swoosh.MailboxPreview.init/1 is undefined (module Plug.Swoosh.MailboxPreview is not available or is yet to be defined)
  lib/foo_web/router.ex:41: FooWeb.Router.__checks__/0

Compilation failed due to warnings while using the --warnings-as-errors option
````

**Comment by princemaple** [comment]
Does it happen if you use swoosh as a local path or git fork dependency, and add an explicit optional dep on plug in swoosh?

Obviously adding an explicit plug dependency in your own app would resolve the warning. Just wondering how swoosh should fix it.

**Comment by mjrusso** [comment]
> Obviously adding an explicit plug dependency in your own app would resolve the warning. 

Hmm, I added `{:plug, "~> 1.14", optional: true}` to my app's mix.exs, but that did not resolve the warning. I tried making it non-optional, but that didn't help either.

As expected, I added `{:plug_cowboy, ">= 1.0.0"}` and that fixed it. The behaviour is strange though; if hackney is included in mix.exs and then I remove plug_cowboy and run:

``` bash
$ mix deps.clean --unused --unlock
* Cleaning cowboy
* Cleaning cowboy_telemetry
* Cleaning cowlib
* Cleaning plug_cowboy
* Cleaning ranch
Unlocked deps:
* cowboy
* cowboy_telemetry
* cowlib
* plug_cowboy
* ranch
```

Sometimes `mix compile --warnings-as-errors --force` will work. To get it to break again, I need to remove hackney, then `mix deps.clean --unused --unlock`, then add hackney back (with associated `mix deps.get`), and then `mix compile --warnings-as-errors --force` will break again.

**Comment by mjrusso** [comment]
I tried this suggestion:

> Does it happen if you use swoosh as a local path or git fork dependency, and add an explicit optional dep on plug in swoosh?

I added swoosh as a local path dependency, and added `{:plug, "~> 1.14", optional: true}` to swoosh's deps, and that appears to fix the issue (or, at the very least, I'm not able to reproduce the issue). FWIW, I don't understand what's happening here 😅

**Comment by princemaple** [comment]
Thank you very much for your exploration. It provides a good base for me to decide what to do next. Cheers.

**Comment by mjrusso** [comment]
@princemaple v1.11.6 works perfectly, thank you!

**Comment by Sinc63** [comment]
@mjrusso I think what you may be running into is something I've reported against elixir itself. See https://github.com/elixir-lang/elixir/issues/12913 for a description. Essentially it's that deps.compile doesn't seem to be reading a previously compiled dependency file to find external references of a current module. You have to explicitly recompile the already compiled file. So when you compile hackney you need to specify plug on the command line, and since it was already compiled also specify force.

**Comment by josevalim** [comment]
I think in this case the fix is correct. Optional dependencies are not transitive: if plug_cowboy is optional, plug isn't optional, and it is not guaranteed it will be available before swoosh. I will investigate the root cause of the Elixir issue next. :)
